namespace VGC.Vehicles;

public enum MavType : byte
{
    Generic = 0,
    FixedWing = 1,
    Quadrotor = 2,
    Coaxial = 3,
    Helicopter = 4,
    AntennaTracker = 5,
    Gcs = 6,
    Airship = 7,
    FreeBalloon = 8,
    Rocket = 9,
    GroundRover = 10,
    SurfaceBoat = 11,
    Submarine = 12,
    Hexarotor = 13,
    Octorotor = 14,
    Tricopter = 15,
    FlappingWing = 16,
    Kite = 17,
    OnboardController = 18,
    VtolDuorotor = 19,
    VtolQuadrotor = 20,
    VtolTiltrotor = 21,
    VtolReserved2 = 22,
    VtolReserved3 = 23,
    VtolReserved4 = 24,
    VtolReserved5 = 25,
    Gimbal = 26,
    Adsb = 27,
    Parafoil = 28,
    Dodecarotor = 29,
    Camera = 30,
    ChargingStation = 31,
    Flarm = 32,
    Servo = 33,
    OpenDroneId = 34,
    Decarotor = 35,
    Battery = 36,
    Parachute = 37,
    Log = 38,
    Osd = 39,
    Imu = 40,
    Gps = 41,
    Winch = 42,
    GenericMultirotor = 43
}
